server:
  port: 8081
spring:
  application:
    name: AUTH
  datasource:
      url: jdbc:mysql://123.56.66.230:3306/demo?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: 1q2w3e4r
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
   mapperLocations: classpath:/mapper/*.xml
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://123.56.66.230:8761/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15