eureka:
  client:
    serviceUrl:
     # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://10.220.20.32:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream

ribbon:
  ConnectTimeout: 5000 #ribbon请求连接的超时时间，默认值2000
  ReadTimeout: 5000 #负载均衡超时时间，默认值5000
  MaxAutoRetries: 0 #对第一次请求的服务的重试次数
  MaxAutoRetriesNextServer: 0 #要重试的下一个服务的最大数量（不包括第一个服务）
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试

zuul:
  ribbonIsolationStrategy: THREAD
  threadPool:
    useSeparateThreadPools: true
    threadPoolKeyPrefix: zuulgateway
  max:
    host:
      max-per-route-connections: 50
      max-total-connections: 300
  host:
    socket-timeout-millis: 5000
    connect-timeout-millis: 50000
  routes:
    OMS-AUTH-SERVER: /auth/**
    OMS-CORE: /core/**
    OMS-API: /api/**
hystrix:
  threadpool:
    default:
      coreSize: 20
      maximumSize: 50
      allowMaximumSizeToDivergeFromCoreSize: true
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 30000

