eureka:
  client:
    serviceUrl:
      defaultZone: http://123.56.66.230:8761/eureka/
  instance:
    prefer-ip-address: true
zuul:
  sensitive-headers:
  host:
    socket-timeout-millis: 5000
    connect-timeout-millis: 50000
  routes:
    AUTH: /auth/**
    CORE: /core/**
server:
  port: 7777
spring:
  application:
    name: zuul
