server:
  port: 7777
spring:
  application:
    name: zuul
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
zuul:
  host:
    socket-timeout-millis: 5000
    connect-timeout-millis: 50000
  routes:
    AUTH: /auth/**
    CORE: /core/**
