server:
  port: 8761
eureka:
  server:
    response-cache-update-interval-ms: 3000
    response-cache-auto-expiration-in-seconds: 180
    eviction-interval-timer-in-ms: 3000
  instance:
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    registerWithEureka: false # 作为服务器，禁止将其自身注册到server上去
    fetchRegistry: false      # 是否需要从Eureka Server上拉取注册信息到本地
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
