server:
  port: 8083
spring:
  application:
    name: CORE
  datasource:
      url: jdbc:mysql://123.56.66.230:3306/demo?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: 1q2w3e4r
      driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath*:mappers/*.xml
logging:
  level:
    com.ck.paper.*.dao: debug

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://123.56.66.230:8761/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15